/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
}

group = "com.github.100mslive"
version = "pre-alpha"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")
}

publishing {
    publications {
        create<MavenPublication>("release") {
            groupId = "com.github.100mslive"
            artifactId = "webrtc"
            version = "m92-4515"

            artifact("../libwebrtc.aar")
    
            pom {
                name.set("WebRTC")
                description.set("A packaging of the webrtc library. Branch-heads/4515")
                url.set("https://webrtc.github.io/webrtc-org/native-code/android/")
                licenses {
                    license {
                        name.set("WebRTC Licence")
                        url.set("https://webrtc.github.io/webrtc-org/license/")
                    }
                }
            }
        }
    }
}
