name: Deploy to dev-in2
on:
  workflow_dispatch:
  push:
    branches:
      - development
      - ravi-test
    paths-ignore:
      - 'kube/values.yaml'
      - 'client/*'
      - 'scripts/*'
      - 'config/*'
      - 'proto/*'
      - '.dockerignore'
      - '.gitignore'
      - 'docker-compose.yml'
      - 'LICENSE'
      - 'README.md'
  
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    env:
      ENV: dev
      VAULT_PREFIX: in2
      DEPLOYMENT_NAME: sfu
      RELEASE_NAME: hmssfu0
      GCP_PROJECT_ID: dev-in2
      GCP_REGION: asia-south1
      GCP_NAMESPACE: ion2
      GCP_CLUSTER: dev-in2
      DOCKER_GIT_TOKEN: ${{ secrets.DOCKER_GIT_TOKEN }}
      ANDROID_SDK_ROOT: ${{ GITHUB_WORKSPACE }}/webrtc_checkout/src/third_party/android_sdk/public/
      ANDROID_HOME: ${{ GITHUB_WORKSPACE }}/webrtc_checkout/src/third_party/android_sdk/public/
      
    steps:

    - name: set environment optimistically
      run: |
        echo "$(pwd)/webrtc_checkout/src/third_party/android_sdk/public/platform-tools" >> $GITHUB_PATH
        echo "$(pwd)/webrtc_checkout/src/third_party/android_sdk/public/tools/" >> $GITHUB_PATH
        echo "$(pwd)/webrtc_checkout/src/build/android" >> $GITHUB_PATH

    - name: prep-steps 
      id: prep-steps
      run: |
        python3 -v 
        df -kh
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools
        pwd
        export PATH=$(pwd)/depot_tools:$PATH
        echo $PATH
        mkdir webrtc_checkout
        cd webrtc_checkout
        fetch --nohooks webrtc_android
        ls -al
        gclient sync --with_branch_heads --with_tags
        cd src  
        git fetch
        git checkout refs/remotes/branch-heads/4515
        gclient sync --with_branch_heads --with_tags 
        
        python3 ./tools_webrtc/android/build_aar.py || exit 0
        ls -alR
        ls -alR "${{ GITHUB_WORKSPACE }}/webrtc_checkout/src/"
        

#    - uses: colpal/actions-clean@v1
#      if: ${{ always() }} 
