name: Build webrtc for android

on:
  workflow_dispatch:
    inputs:
      webrtcBranchId:
        description: 'The branch id to build. This should be in the release notes for webrtc.'
        required: true
        default: '4577'

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    env:
      ENV: dev
      VAULT_PREFIX: in2
      DEPLOYMENT_NAME: sfu
      RELEASE_NAME: hmssfu0
      GCP_PROJECT_ID: dev-in2
      GCP_REGION: asia-south1
      GCP_NAMESPACE: ion2
      GCP_CLUSTER: dev-in2
      DOCKER_GIT_TOKEN: ${{ secrets.DOCKER_GIT_TOKEN }}
      
    steps:
    - name: Confirm inputs
      run : |
        echo ${{ github.event.inputs.webrtcBranchId }}
        echo "refs/remotes/branch-heads/${{ github.event.inputs.webrtcBranchId }}"
        
    - name: set environment optimistically
      run: |
        echo "$(pwd)/webrtc_checkout/src/third_party/android_sdk/public/platform-tools" >> $GITHUB_PATH
        echo "$(pwd)/webrtc_checkout/src/third_party/android_sdk/public/tools/" >> $GITHUB_PATH
        echo "$(pwd)/webrtc_checkout/src/build/android" >> $GITHUB_PATH
        echo "ANDROID_SDK_ROOT=$(pwd)/webrtc_checkout/src/third_party/android_sdk/public/" >> $GITHUB_PATH
        echo "ANDROID_HOME=$(pwd)/webrtc_checkout/src/third_party/android_sdk/public/" >> $GITHUB_PATH
        echo "INITIAL_RUN_DIRECTORY=$(pwd)" >> $GITHUB_PATH
        echo $ANDROID_HOME
        echo "$INITIAL_RUN_DIRECTORY"

    - name: get depot tools
      id: get-depot-tools
      run: |
        python3 -v 
        df -kh
        echo "$(pwd)/depot_tools" >> $GITHUB_PATH

    - name: Get necessary tools
      run: |
        sudo apt-get install aptitude -y
        sudo apt-get update
        sudo apt-get clean
        sudo aptitude -y install g++-arm-linux-gnueabihf gcc-multilib

#     - name: clone 
#       id: clone
#       working-directory: ./webrtc_checkout
#       run: |
#         fetch --nohooks webrtc_android
#         ls -al
#         gclient sync --with_branch_heads --with_tags

    - name: checkout release branch
      id: checkout_release_branch
      working-directory: ./webrtc_checkout/src
      run: |
        echo "refs/remotes/branch-heads/${{ github.event.inputs.webrtcBranchId }}"
        git fetch
        git checkout "refs/remotes/branch-heads/${{ github.event.inputs.webrtcBranchId }}"
        gclient sync -D --with_branch_heads --with_tags 


    - name: install dependencies
      id: install_dependencies
      working-directory: ./webrtc_checkout/src
      run: |
        ./build/install-build-deps.sh --no-prompt

    - name: install patches if present
      id: install_patches
      working-directory: ./webrtc_checkout/src/
      run: |
        ls
        ls ../
        ls ../../

    - name: build
      id: build
      working-directory: ./webrtc_checkout/src
      run: |
        python3 ./tools_webrtc/android/build_aar.py

    - name: Upload a Build Artifact library
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "libwebrtc-${{ github.event.inputs.webrtcBranchId }}.aar"
        path:
          ./webrtc_checkout/src/libwebrtc.aar

    - name: Upload a Build Artifact licence
      uses: actions/upload-artifact@v2.2.4
      with:
        name: LICENSE.md
        path:
          ./webrtc_checkout/src/LICENSE.md

#    - uses: colpal/actions-clean@v1
#      if: ${{ always() }} 
